<?php
/*
Template name: Page - BMI Full Width
*/
get_header(); ?>

<?php do_action( 'flatsome_before_page' ); ?>

<div id="content" role="main" class="content-area">
			<div id="wp-vue-app">
				This text will be replaced by the Vue App when the SPA build (generated by Webpack) is enqueued in WordPress.
			</div><!-- #vue-app -->
		
</div>

<?php do_action( 'flatsome_after_page' ); ?>

<?php get_footer(); ?>
